### ISSUE TITLE
Infer installs infer.exe binary

### ISSUE THREAD

**Issue by yakobowski** [facebook/infer#1059]
[Background: I'm trying to make Infer compile under Windows. I will be submitting issues and PR to this effect.]

The infer Makefiles build and install a `infer.exe` binary, next to the 'naked' `infer` one [1]. This is somewhat weird, as Infer cannot be built on Windows currently. This would be of little consequence, except for this:

http://cygwin.1069669.n5.nabble.com/cp-utility-bug-when-dest-name-exe-file-exist-tp57955p58001.html

Basically, Cygwin won't install an executable binary if there is already an existing file with a `.exe` extension. So the above-mentioned part of the Makefile is not portable.

If, as I suspect, the `.exe` binary is not useful under Linux/MacOSX, I can propose a patch that prevents it from being installed. This will simplify the Windows build.

[1] https://github.com/facebook/infer/blob/4d46f8631e5d7fbbc51bc36c8e52429aee310a06/infer/src/Makefile#L132

**Comment by jvillard** [comment]
Interesting... The .exe file comes from dune, so I don't know how to do it differently. Or is the issue in the line *after* the one you pasted?

https://github.com/facebook/infer/blob/4d46f8631e5d7fbbc51bc36c8e52429aee310a06/infer/src/Makefile#L133

Basically that line exists so that it's easy to make sure to use the optimised binary (.exe) and not the bytecode version (.bc) of infer, in the context of building infer successively in one mode and the other. However it's a minor convenience so it could go away (I think, unless other tests in the repo depend on that), or at least give the .exe a different extension.

**Comment by yakobowski** [comment]
The faulty (if faulty can be used here, the culprit is mostly Cygwin) line is indeed the second one, but it is not possible to make a permalink over two lines.

> Basically that line exists so that it's easy to make sure to use the optimised binary (.exe) and not the bytecode version (.bc) of infer, in the context of building infer successively in one mode and the other.

I see, I did not realize that. There are indeed two "competing" lines for `$(INFER_BIN).exe` and `$(INFER_BIN).bc`. 

I will try to find an installation scheme that makes Cygwin happy, maybe by removing first the existing binaries. I will keep you posted.

**Comment by yakobowski** [comment]
I pushed a fix for this issue in #1060. I had to go for a windows-only snippet of code, because all other solutions had drawbacks. (I particular, if we do not want to remove `infer.exe` when compiling `infer.bc`).

**Comment by yakobowski** [comment]
Closed by https://github.com/facebook/infer/commit/31a6b92902f6166d8c7f4ccac21a1de1bb9c0c4f
