### ISSUE TITLE
Enable all warnings for C/C++ code

### ISSUE THREAD

**Issue by orbitcowboy** [facebook/infer#1114]
What commandline options are recommended to get a maximum of output for scanning C/C++ code?

**Comment by jvillard** [comment]
There are two ways to get infer to report more: enable more checkers, and let the checkers report more issues. Just as a word of caution I wouldn't recommend doing either, the defaults should already enable all the checkers and issues that give reasonably good signal.

To see what checkers are available you can look for `*-only` options in `infer --help` (I guess it would be helpful to list them all somewhere in there too...). However, most if not all of the checkers disabled by default are disabled because they are experimental or generally giving poor signal.

To open the floodgates on the reported issues you can use `--no-filtering`.

**Comment by orbitcowboy** [comment]
Thank you for explaining these options. I was using it with default options so far. It is worth to see what `--no-filtering` brings up.

Overall the documentation of infer checks could be improved a little by mentioning the affected language. This is not always the case.

Many thanks for this great tool and all the hard work.
