### ISSUE TITLE
Timezone Error when using released binary

### ISSUE THREAD

**Issue by ckddls1321** [facebook/infer#1158]
- Infer version v0.17.0 
- Ubuntu 18.04.3 Bionic 
- just command infer 
- (anaconda3-5.2.0) {19-10-01 10:08}ckddls1321:~/toolchain/infer/examples ckddls1321% 
infer -gcc -c hello.c
Uncaught Internal Error: ("unknown zone" (zone ASIA/Seoul))
Error backtrace:
Raised at file "src/error.ml" (inlined), line 9, characters 14-30
Called from file "src/error.ml", line 11, characters 19-40
Called from file "camlinternalLazy.ml", line 27, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 34, characters 4-11
Called from file "base/RunState.ml", line 10, characters 22-51
- I used official example with released version. hello.c, hello.m

**Comment by jvillard** [comment]
I can reproduce locally with `TZ=ASIA/Seoul infer`. As a workaround you can run `unset TZ` before running `infer`.

It looks like you should have "/usr/share/zoneinfo/ASIA/Seoul" be a valid path, or `$TZDIR/ASIA/Seoul` if `TZDIR` is set in your environment. On my machine (Debian bullseye) that path doesn't exist but "Asia/Seoul" (notice "Asia" instead of "ASIA") does, so perhaps `TZ=Asia/Seoul infer` works too?

**Comment by jvillard** [comment]
Please re-open if you have further issues with that.

**Comment by mindhells** [comment]
I faced the same problem running infer from a Docker container based on ubuntu:18:04.
If I unset TZ infer complains about /etc/localtime not exists. 
I had to install de package "tzdata" to get rid of it (you don't need to unset the timezone).
