### ISSUE TITLE
Trying to detect integer overflow from UBSan example

### ISSUE THREAD

**Issue by adrianherrera** [facebook/infer#1203]
I am trying to use Infer to detect the integer overflow in the following code, adapted from LLVM's [UndefinedBehaviourSanitizer](https://github.com/llvm-mirror/clang/blob/master/docs/UndefinedBehaviorSanitizer.rst#usage) (the only difference is that I return k, so it does not get reported as dead):

```c
// test.c
int main(int argc, char **argv) {
  int k = 0x7fffffff;
  k += argc;
  return k;
}
```

I run as follows (on Ubuntu 18.04):

```bash
% infer --version
Infer version v0.17.0
Copyright 2009 - present Facebook. All Rights Reserved.
% CC=clang-8 infer -- cc -m32 test.c -O0 -g # I've also tried without the `-m32`
Analysis finished in 555mss

  No issues found  
```

Do you know why Infer isn't able to detect this (seemingly trivial) integer overflow? Are there some flags that I should be enabling?

**Comment by skcho** [comment]
First please note that detecting integer overflow in Infer is **experimental** for now.

Infer does not raise an alarm in your example because:
* In the integer overflow checking, it does not address `argc` specifically as of now. On the other hand, in order to raise an integer overflow alarm there, it should know that given `argc` is always bigger than 0.
* It requires an additional flag `--bufferoverrun`, which has been developed for detecting buffer overrun originally, but has a lot of false positives at the moment unfortunately.

So, if you run this,

```
// a.c
int foo(int argc) {
  int k = 0x7fffffff;
  k += argc;
  return k;
}

void goo() {
  foo(1);
}
```
you would get the following result.
```
$ infer --bufferoverrun -- gcc -c a.c
Found 1 issue

a.c:9: error: INTEGER_OVERFLOW_L1
  (2147483647 + 1):signed32 by call to `foo`.
  7.   
  8.   void goo() {
  9. >   foo(1);
  10.   }


Summary of the reports

  INTEGER_OVERFLOW_L1: 1
```

I hope this helps.

**Comment by adrianherrera** [comment]
Yes, that helps a lot!! Thank you soooo much.
