### ISSUE TITLE
False positive DEAD_STORE

### ISSUE THREAD

**Issue by kalman5** [facebook/infer#1204]
Version:   v0.17.0
OS: Linux Kubuntu 19.10
Command: infer run -- g++ main.cpp

main.cpp contains:

```
#include <iostream>

void foo() {
  if (rand() > RAND_MAX/2) {
    throw std::runtime_error("bam");
  }
}

int main() {
    srand(time(nullptr));

    bool myExceptionRaised = true;
    try {
      foo();
      myExceptionRaised = false;
    } 
    catch (...) {
    }

    if (myExceptionRaised) {
      std::cout << "0\n";
    } else {
      std::cout << "1\n";
    }
}
```

the following claim is wrong

```
Capturing in make/cc mode...
Found 1 source file to analyze in /home/kalman/infer-out


Analysis finished in 529mss

Found 1 issue

main.cpp:12: error: DEAD_STORE
  The value written to &myExceptionRaised (type _Bool) is never used.
  10.       srand(time(nullptr));
  11.   
  12. >     bool myExceptionRaised = true;
  13.       try {
  14.         foo();


Summary of the reports

  DEAD_STORE: 1
```

**Comment by jvillard** [comment]
Thanks for the report. What's happening at the moment is this: infer doesn't really translate exception control flow except at the very end of the `try` block where it inserts an exceptional edge to the `catch` block in the control-flow graph. In this example the code will look like it's always writing over the `true` store with the `false` store. You could circumvent this issue by doing `myExceptionRaised = true` in the `catch` block instead of at initialisation time. To tackle the issue more generally we need a better way to deal with exceptions in C++ or a clever hack to make this problem go away for dead stores.

**Comment by jvillard** [comment]
Infer no longer reports false positives of this sort. Thanks again for the report.
