### ISSUE TITLE
Fbinfer.com contains wrong information about registering checkers

### ISSUE THREAD

**Issue by Rui1995** [facebook/infer#1224]
Hi.

I am trying to register the SimpleChecker already available in "/infer/src/SimpleChecker.ml" (didn’t change the code), following the instruction from https://fbinfer.com/docs/adding-checkers.html (adding to "all_checkers" in registerCheckers.ml):

let all_checkers =
   [ { name= "my simple checker"
     ; active= true
     ; callbacks= [(Procedure SimpleChecker.checker, Language.Java)] }
   ; (* the rest of the list as it was there *)
     ... ]

While compiling (doing “sudo ./build-infer.sh java”) the following error occurs:

https://gist.github.com/Rui1995/11f9d297bc980bbb4df07052639c64bb

I’m running on Ubuntu 18.04 and the Infer version is  v0.17.0-75e52f1f1.

Apologies if there’s not enough information or wrong formatting, this is the first issue that I’ve opened.

**Comment by ezgicicek** [comment]
Hi,
You can't directly register the existing `SimpleChecker` because, albeit the name, it is not a checker but a checker maker. In other words, it contains a functor that takes a domain specification and returns a checker. 

To get a checker, you need to first implement your appropriate domain specification (which contains type of your state, how to compare your states, your transfer functions, and when to report). Then, instantiate the functor `SimpleChecker.Make` with this spec.

For instance, if you call your domain spec `MyDomainSpec`, then `SimpleChecker.Make(MyDomainSpec)` will give you the checker, which can be registered. 

A very simple checker which does nothing would be:
```
module MyDomainSpec = struct
  (** dummy state *)
  type t = unit

  let initial  = ()


  let exec_instr astate instr node proc_name env : t = astate 
  (** dummy transfer function that simply returns given state.  *)

  let report astate loc proc_name  = ()
  (** log errors here. *)

  let compare astate1 astate2 = 0
  (** dummy compare *)
end

module MySimpleChecker = SimpleChecker.Make(MyDomainSpec)
```
Now, you can register your checker by refering to `MySimpleChecker.checker`. 


Obviously, the above checker is useless. You want to pick the appropriate domain type and implement the comparison, reporting and transfer functions correspondingly.

**Comment by Rui1995** [comment]
Thanks you for your answer. 

I believe I understand it now.

Best Regards.
