### ISSUE TITLE
Switch from Travis to GitHub Actions

### ISSUE THREAD

**Issue by imbsky** [facebook/infer#1270]
We recently created [setup-ocaml](https://github.com/avsm/setup-ocaml). If you are okay, I would like to switch to that.

**Comment by jvillard** [comment]
Thanks for bringing that up, it makes sense to switch. We'd very much welcome a PR in that direction.

Some further thoughts: I imagine that switching to a GitHub action could also let us automatically publish things like Docker images in the future. I'd love to have GitHub actions to even automatically build release tarballs! Currently new releases are a pain to make because someone has to update the scripts that build the tarballs every time as they suffer from bitrot in-between versions. Building them on every commit or so would flag these regressions faster. The main challenge would be finding a way to either build clang from GitHub actions (it takes too long for Travis!) or ship separate releases of just clang+plugins and use these. I'm hoping to have time to look into the latter at some point. Anyhow, I digress.

**Comment by imbsky** [comment]
I'm glad to hear that. Huh, I think that probably it's possible.

**Comment by Amar1729** [comment]
Huh. I completely missed this work, but @jvillard for visibility: I think I've managed getting facebook-clang-plugins' clang building using github actions here:

https://github.com/facebook/facebook-clang-plugins/pull/20
