### ISSUE TITLE
Undocumented influence between checkers?

### ISSUE THREAD

**Issue by hmijail** [facebook/infer#1363]
Infer version v1.0.0-0c6eedc83
MacOS Catalina 10.15.7 (19H114)

Issue #1362 shows that checkers influence each other. This doesn't seem to be documented anywhere. Is this a bug? 

If not, it'd be good to have some guidance regarding whether it's best to run various checkers together or isolated from each other. For example, does it affect the depth of the analysis somehow?

Particularly for #1362, Eradicate is not shown to relate to any other checker in `infer --list-checkers`. And `infer --help-checker eradicate` does not show any information, and instead seems to run an analysis with the default checkers (which I guess is another bug)

**Comment by jvillard** [comment]
Thanks for bringing this up. The checkers don't influence each other, but activating inter-procedural checkers will cause intra-procedural checkers to analyse functions they wouldn't have bothered looking at otherwise. This is because of the following interaction:
- Each procedure to analyse is always analysed by *all* the active checkers
- Intra-procedural checkers don't need to analyse callees to go past function calls in a procedure, eg `foo() { goo(); }` won't trigger an analysis of `goo()` if only intra-procedural checkers like eradicate are enabled.
- Inter-procedural checkers, on the other hand, very much do go into callees: analysing `foo()` above will first trigger an analysis of `goo()`.

That said, in most cases all procedures in the project are analysed anyway so this shouldn't matter unless you pass `--reactive` or `--changed-files-index`. I'm not sure what happened exactly in your case that is hiding some procedures from the analysis and makes them only analysed as callees, but it could be dynamic dispatch resolution or something similar as infer can synthesise new methods in that case. You can double check by disabling only biabduction, which is currently the only analysis that does that.

Note also that `--help-checker` is part of the `help` subcommand so you need to run `infer help --help-checker eradicate` to get information on eradicate.

**Comment by jvillard** [comment]
I think this is resolved now but please feel free to reopen.

**Comment by hmijail** [comment]
> Note also that --help-checker is part of the help subcommand so you need to run infer help --help-checker eradicate to get information on eradicate.

Thank you, that works. 

However, I'd still want to bring attention to the fact that `infer --help-checker eradicate` does not report any error, AND it does syntax-check the parameters (so `--help-chekerS eradicate` or `--help-checker asdf` both report errors). 

So having that lack of errors made it feel like it was really working as expected. I'd suggest that it'd be better to have an explicit error.
