### ISSUE TITLE
Infer ignores TypeQualifierNickname annotations

### ISSUE THREAD

**Issue by denizt** [facebook/infer#142]
We have an `NotNull` annotation that is a `TypeQualifierNickname` for `javax.annotation.Nonnull`, however infer does not take this into account and thinks a `NotNull` method instance can be `null` as it was defined `Nullable` in class scope.

```java
@Nullable
String mStr;

public void parse(@NotNull String str) {
    //str nonnull here
   mStr = str;
    print mStr.length();
} 
```

**Comment by sblackshear** [comment]
This was fixed by 7821266c8feec03b7edf157d474e6a5ec364499f. Note that this will work even without the `@NotNull` annotation (which Infer actually doesn't understand); Infer will figure out that `str` must be non-null in order for the `parse` procedure to be safe, and it will complain if a caller of `parse` passes a possibly-null value.
