### ISSUE TITLE
Invoking `infer -g run  -- mvn compile` command from Infer REPL

### ISSUE THREAD

**Issue by jeongsoolee09** [facebook/infer#1453]
My Environment is like the following:
- My Infer is of version 1.0.0.
- I am on macOS Big Sur.
- I usually run Infer with `infer -g run -- mvn compile`.

Hello, I was wondering if I could invoke Infer's capture and analyze facilities from the Infer-REPL. So I have looked into onDemand.ml and Maven.ml, but I still have no idea where the entry point to Infer is when I use the above command. I guess if I can get that 'main' procedure I might be able to capture and analyze from the comfort of Utop (Yes, I *love* Utop 🙃).

Could you please give some guidance to what I want to achieve?

**Comment by jvillard** [comment]
Very entertaining, thanks :) We don't link the toplevel infer.ml file into the toplevel because it also runs infer when loaded, which wouldn't be desirable: https://github.com/facebook/infer/blob/dfd4dd44dd589b92ce864dd22b01ab043e2a9cbc/infer/src/dune.in#L94-L108

The functions in infer.ml could live somewhere else though, and infer.ml could just contain a single line `let () = InferMain.run ()`.

You'd still have to restart utop everytime you want to give different config options to infer though.

**Comment by jeongsoolee09** [comment]
@jvillard After some fiddling, I managed to scratch my own itch: invoking `infer analyze -- mvn compile` from Utop. Essentially, I extracted the `let () = ...` phrase in `src/infer.ml`, selected the relevant parts triggered by the above command, and wrapped those in a separate function. This lives in a new submodule declared as a library, under the directory `src/Repl`. [https://gist.github.com/jeongsoolee09/82c92f99a4fc17438161de243772386a][The code is shown in this gist.]

One inconvenience is that I might have to use the `#cd` directive to change the working directory of Utop, but that's quite minor!

Thanks for your guidance, and I am going to close this thread.
