### ISSUE TITLE
Infer does not report a memory leak bug

### ISSUE THREAD

**Issue by endjkv** [facebook/infer#1457]
Infer does not report a memory leak in the below C code: 
```c
struct Person {};

void memory_leak_bug() {
    struct Person *p = malloc(sizeof(struct Person));
}
```
This is an example from the official [doc](https://fbinfer.com/docs/all-issue-types#memory-leak-in-c).

The command is `infer-run -- gcc -c main.c`.

The output is as below:
```
main.c:4: error: Dead Store
  The value written to &p (type Person*) is never used.
  2. 
  3. void memory_leak_bug() {
  4.     struct Person *p = malloc(sizeof(struct Person));
         ^
  5. }


Found 1 issue
  Issue Type(ISSUED_TYPE_ID): #
      Dead Store(DEAD_STORE): 1
```

I have tried the pre-built binaries of v1.1.0, v1.0.0, v0.17.0, and I also compiled v1.1.0 from source.

None of them found the memory leak bug.

I couldn't find any issues related to this, did I miss something?

**Comment by jvillard** [comment]
First I was going to comment that this is because of the empty struct having size 0 (and actually empty structs are not allowed in C but compilers give it a pass), but actually it's unclear that it isn't a leak, and more importantly I get the false negative with valid structs too.

The analysis that detects leaks is called "biabduction" but is not being looked after very well.

The solution here is to switch to the new Pulse analysis, which is still in development and aims at replacing biabduction as the default in the coming months. Pulse finds the memory leak here. Run with `infer --pulse-only -- gcc -c -main.c`.
