### ISSUE TITLE
Chinese documentation link

### ISSUE THREAD

**Issue by liaohuqiu** [facebook/infer#164]
I've done some translated work for Chinese documentation, you we add a link for this kind resource?

http://infer.liaohuqiu.net/

**Comment by jvillard** [comment]
Hi @liaohuqiu, thanks a lot for your contribution, this is great! We'd be happy to link to your website.

We recently updated the website. Would you mind getting the translation up to date before we link to it? In particular http://infer.liaohuqiu.net/docs/getting-started.html and http://infer.liaohuqiu.net/support.html, especially the first one since these instructions are no longer valid and point to broken links.

**Comment by feilongzheng** [comment]
Hi@liaohuqiu 
I looked http://infer.liaohuqiu.net/docs/getting-started.html and http://fbinfer.com/docs/getting-started.html.
There is a lot of differences between them.

**Comment by liaohuqiu** [comment]
Sorry guys. I was busy in looking for my next job and can not update the document. Now I think everything is almost settle down. I will update it soon. Can you assign this issue to me?

**Comment by jvillard** [comment]
@liaohuqiu that's great to hear! Unfortunately only contributors with push access can be assigned issues from GitHub.

**Comment by jvillard** [comment]
Hi @liaohuqiu, do you have any news about updating your website? The installation instructions are out of date and this is causing confusion for our users (see eg #342).

Many thanks.

**Comment by jvillard** [comment]
Please re-open if you find time to update your translation to a more recent version.
