### ISSUE TITLE
[pulse] Handling Third-Party Library Calls when Analysing Projects

### ISSUE THREAD

**Issue by Robsterbobster** [facebook/infer#1814]
Hello, I am using Pulse to analyse a C project that assumes some third-party libraries are installed before compilation. In that C project, there are some calls to third-party library functions. If I analyse this project, these calls can be treated as unknown and thus give inaccurate results. I have the third-libraries source codes and I can run pulse on them, is there any features in Pulse or things I can do to address this problem?

**Comment by jvillard** [comment]
Hi @Robsterbobster, if you have a way to expose the code of library functions to infer then you should be able to have infer take them into account. One way to do this is to capture libraries and then the project in the same infer-out/ with `--continue`. Something like this:

```
# first library
$ cd ~/code/lib1
$ infer capture -o /tmp/infer-out -- make -j 8
# second library
$ cd ~/code/lib2
$ infer capture --continue -o /tmp/infer-out -- make -j 8
# main project
$ cd ~/code/project
$ infer capture --continue -o /tmp/infer-out -- make -j 8
$ infer analyze -o /tmp/infer-out
```

If you also want infer to report on library code then all of these should share a common project root (here that would be `--project-root ~/code`).

Alternatively, you can also look into the various `--pulse-model-*` options to specify what some of these functions do in basic terms if it turns out that a few library functions are causing most of the precision loss.

**Comment by Robsterbobster** [comment]
Hi @jvillard, that works! Thank you very much for your help!
