### ISSUE TITLE
Inheritance and interfaces in modelling

### ISSUE THREAD

**Issue by pontusbostrom** [facebook/infer#185]
I use a rather large third party library of components and I would like to model its behaviour. To make the work manageable I would like to model methods in the classes highest in the class hierarchy. Additionally it would be very useful to model interfaces. E.g. it would be convenient to model the List interface instead of providing identical models for every list implementation.

-It seems method models are not inherited. Is this correct or did I make a mistake somewhere?
-Are there plans to support modelling of interfaces?

**Comment by jeremydubreil** [comment]
Unfortunately, it does not work right now to model the interfaces in order to model all the implementations at once. This is due to an incomplete support for dynamic dispatch in the analyzer. For example, if a method is of the form:

```java
int foo(List l) {
    return l.lenght();
}

int bar(ArrayList l) {
  return foo(l);
}
```

Then the model provided for `List.length()` will not be used in the call to `foo(l)` in `bar`.

I am leaving this task opened for now as this are things that we are working on.

However, if you model a method in a class `A`, then you do not need to model it again in the subclasses of `A`.

**Comment by pontusbostrom** [comment]
Thank you for your reply and for describing the current situation in the tool! Good to hear that support for modelling interfaces is in the plans

**Comment by jvillard** [comment]
@jeremydubreil Is there an update on this issue of supporting inheritance and interfaces in the Java models?

**Comment by jeremydubreil** [comment]
@pontusbostrom In general, we are trying to move away from having models in source code, i.e. in Java, in favor of having the models builtin the OCaml code. The later approach is more flexible and allows to model the same method differently for different analysis backends.
