### ISSUE TITLE
how can i use Facebook infer in android studio ?

### ISSUE THREAD

**Issue by raghavsatyadev** [facebook/infer#186]

**Comment by jeremydubreil** [comment]
You should be able to run Infer from the command line if your projects are using Gradle for the compilation.

If your question is about having Infer integrated with the IDE, there is no real support for this. However, you may be able to get your Infer reports inlined in the IDE if you use `infer -- gradle` as build command instead of `gradle`, but this has probably never been tried.

**Comment by raghavsatyadev** [comment]
thank you for your support

**Comment by kumarbanty** [comment]
When i am running the command infer -- ./gradlew build i am getting the error which is shown in the screenshot. I am not really sure what this means because my project runs fine. Can I get some help with this
![image](https://cloud.githubusercontent.com/assets/19968540/16147807/1aa8b0fe-34a3-11e6-9165-0d35e5813e5f.png)

**Comment by sblackshear** [comment]
Could you post the full output of running `./gradlew build` and `infer -- ./gradlew build`?

**Comment by kumarbanty** [comment]
I am getting the exact same error in both error with both the commands which I have posted earlier

**Comment by kumarbanty** [comment]
Here is the full output of infer --./gradlew build command I am getting the same thing with ./gradlew build
I have researched a lot and I have tried all the clean, build, rebuild options as suggested by various websites but nothing works.
<img width="1440" alt="screen shot 2016-06-20 at 3 36 32 pm" src="https://cloud.githubusercontent.com/assets/19968540/16190422/cd1e5aee-36fc-11e6-8f81-aa102183645e.png">

**Comment by JeffreyLeeSpokeo** [comment]
I know that last year jeremy says that there is no integration with the IDE. is that still the case now?
