### ISSUE TITLE
0.5.0 source tarball is missing facebook-clang-plugin files.

### ISSUE THREAD

**Issue by tonycosentini** [facebook/infer#233]
It look like the tarball and zip file for the 0.5.0 don’t have the facebook-clang-plugin submodule included. Is there anyway someone can create another archive for this release with the missing files?

I have a working Homebrew formula I’d like to submit to Homebrew for this release, but it won’t compile without the clang plugin files.

(Also, if you're wondering why Homebrew needs the source and not the binary, here's a pretty good explanation of why they prefer building from source: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#we-dont-like-binary-formulae)

**Comment by jvillard** [comment]
The "Source code" links are auto-generated by GitHub. The other ".tar.xz" files contain infer + plugins source code (not precompiled), and a precompiled custom clang, because clang takes so long to compile (1+ hour on most laptops).

Is the pre-compiled clang an issue? If so, we can add another tarball with only the sources.

**Comment by tonycosentini** [comment]
I see, I think the hand-created ones should be fine then. Sorry for the misunderstanding, thanks for the quick reply!
