### ISSUE TITLE
-i flag will return no issues when using multiple analyzers.

### ISSUE THREAD

**Issue by tonycosentini** [facebook/infer#255]
It seems like Infer does not keep separate caches for different analyzers. This can result in surprising empty analysis runs (unless I'm doing something wrong).

I'm testing with this Java file:
```java
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;

public class Test {

	private List<String> mList;

	public Test() {
	}

	public String string() {
		return null;
	}
}
```

It should generate 0 Infer warnings and 1 Erradicate warning (because of a missing `@Nullable`).

If I run Infer with `-i -a infer` first, and then `-i -a eradicate`, it will assume there is nothing to analyze for Eradicate and incorrectly report no warnings:
```
➜  eradicate_collections  infer -i -a capture -- javac Test.java
➜  eradicate_collections  infer -i -a infer -- analyze
Starting analysis (Infer version v0.6.0)
Computing dependencies... 100%
Analyzing 0 clusters
Analyzed 0 procedures in 0 files
No issues found
➜  eradicate_collections  infer -i -a eradicate -- analyze
Starting analysis (Infer version v0.6.0)
Computing dependencies... 100%
Analyzing 0 clusters
Analyzed 0 procedures in 0 files
No issues found
➜  eradicate_collections
```

If I run Eradicate first, it properly finds the missing annotations:
```
➜  eradicate_collections  infer -i -a eradicate -- analyze
Starting analysis (Infer version v0.6.0)
Computing dependencies... 100%
Analyzing 1 cluster. 100%
Analyzed 2 procedures in 1 file

Found 2 issues
Test.java:9: error: ERADICATE_FIELD_NOT_INITIALIZED
  Field `Test.mList` is not initialized in the constructor and is not declared `@Nullable`
  07.   	private List<String> mList;
  08.
  09. > 	public Test() {
  10.   	}
  11.

Test.java:12: error: ERADICATE_RETURN_NOT_NULLABLE
  Method `string()` may return null but it is not annotated with `@Nullable`. (Origin: null constant at line 13)
  10.   	}
  11.
  12. > 	public String string() {
  13.   		return null;
  14.   	}
➜  eradicate_collections  infer -i -a infer -- analyze
Starting analysis (Infer version v0.6.0)
Computing dependencies... 100%
Analyzing 0 clusters
Analyzed 0 procedures in 0 files
No issues found
➜  eradicate_collections
```

**Comment by jeremydubreil** [comment]
@tonycosentini: Unfortunately, you cannot use Infer and Eradicate using the same out directory because the analysis data are not compatible. This is not a theoretical limitation but it will require a good amount of changes to support this use case. Is it possible in your setting to just make a copy of `infer-out` after `infer -a capture` and before running the analysis ?

Besides, I think that the `-i` option is not compatible with running the analysis in two steps using:

  `infer -a capture --`

followed by:

  `infer -- analyze`

Is the approach or running:

  `infer -i -a eradicate -o eradicate-out -- ...`

and independently:

  `infer -i -a infer -o infer-out -- ...`

blocking for you ?

**Comment by tonycosentini** [comment]
Thanks for the response!

We were hoping to do one capture to cut down on time. We can split it up though.

It would be nice to fail when using `-i` incorrectly - it's kind of hard to tell what is supported and what is not (I can give this a try, should be somewhat easy since it's in the Python code).
