### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by technion** [facebook/infer#270]
Hi,

I seem to have some issues with the docker build. Using the provided Dockerfile:

```
Step 10 : RUN cd /infer &&     eval $(opam config env) &&     make -C infer clang java
 ---> Running in 7d087081c6a2
[WARNING] Running as root is not recommended
make: Entering directory '/opt/infer-linux64-v0.6.0/infer'
make: Leaving directory '/opt/infer-linux64-v0.6.0/infer'
make: *** No rule to make target 'clang'.  Stop.
The command '/bin/sh -c cd /infer &&     eval $(opam config env) &&     make -C infer clang java' returned a non-zero code: 2
```

The beauty of Docker is that I don't think there's a lot of room for much to go wrong - any assistance appreciated.

**Comment by kstreee** [comment]
It may works if you add './configure &&' command after the command 'eval $(opam config env) &&', but it also fails because of ocaml version.
The error message shown because of ocaml version is,
```
File "clang/cLocation.ml", line 76, characters 11-12:
Error: Syntax error
Command exited with code 2.
Makefile:187: recipe for target 'build_clang' failed
make[1]: *** [build_clang] Error 10
make[1]: Leaving directory '/opt/infer-linux64-v0.6.0/infer/src'
Makefile:21: recipe for target 'clang' failed
make: Leaving directory '/opt/infer-linux64-v0.6.0/infer'
make: *** [clang] Error 2
The command '/bin/sh -c cd /infer &&     eval $(opam config env) &&     ./configure &&     make -C infer clang java' returned a non-zero code: 2
```
And the build fail message comes from https://github.com/facebook/infer/blob/6389cb9bd0c47b21c72a2aa3532d0301ddb218fc/infer/src/clang/cLocation.ml#L76.
The syntax does not work with ocaml 4.01, and the ocaml installation command ( https://github.com/facebook/infer/blob/master/docker/Dockerfile#L20 ) installs ocaml 4.01.
Thus we need to change ocaml version using opam, ( opam switch 4.02.3 ).

I am currently trying to fix it and after I am done, I will send a pull request for it.

**Comment by technion** [comment]
Thanks! I can confirm, I've managed to get that exact error out of this issue, so it does appear you've got it covered.

**Comment by kstreee** [comment]
@technion I sent a pull request to solve it, so if you need it right now, you can try it. It works for me. https://github.com/facebook/infer/pull/271

**Comment by jimmyxu0311** [comment]
excute 'make -C infer java' prompt 'make: *** No rule to make target `java'.  Stop.',I don't konw solution,can you tell me reason?

**Comment by kstreee** [comment]
@jimmyxu0311 Try that again after run ```./configure``` command.

**Comment by Hellengo** [comment]
make -C infer java
make: *** No rule to make target `java'.  Stop.

./configure
zsh: no such file or directory: ./configure

help
