### ISSUE TITLE
False positive with two strange fixes

### ISSUE THREAD

**Issue by wouter89** [facebook/infer#344]
I've found the following construct in my Java code (Example 1), which Infer doesn't analyse correctly (made simpler to better illustrate the problem) 

I've also found two small changes to the code that result in Infer correctly analysing the code (Examples: 3 - 6). I don't understand why these changes do lead to a correct report from Infer, maybe there is a bug to be found here.

I'm running version 0.8.0

Problem:
--------
**Example 1: False positive**
```java
public class Program {
	public static void main(String[] args){
		NoNullDereference noNullDereference = new NoNullDereference();
		noNullDereference.test();
	}
}

class NoNullDereference{
	private boolean alwaysFalse = false;	
	
	public void test(){
		String data;
		if(alwaysFalse){
			data = null;
		}else{
			data = "hello ";
		}
		
		data.trim();
	}
}
```

```
Program.java:19: error: NULL_DEREFERENCE (backend/rearrange.ml:1007:57-64:)
  [B1] object data last assigned on line 14 could be null and is dereferenced at line 19
  17.   		}
  18.   		
  19. > 		data.trim();
  20.   	}
  21.   }
```
------------------
**Example 2: True positive (by accident?)**

```java
  public class Program {
	public static void main(String[] args){
		NullDereference nullDereference = new NullDereference();
		nullDereference.test();
	}
}

class NullDereference{
	private boolean alwaysTrue = true;	
	
	public void test(){
		String data;
		if(alwaysTrue){
			data = null;
		}else{
			data = "hello ";
		}
		
		data.trim();
	}
}
```
```
Program.java:19: error: NULL_DEREFERENCE (backend/rearrange.ml:1007:57-64:)
  [B1] object data last assigned on line 14 could be null and is dereferenced at line 19
  17.   		}
  18.   		
  19. > 		data.trim();
  20.   	}
  21.   }
```

Fix 1: Moving the trim() function outside the class
----------------

**Example 3: True positive**
```java
  public class Program {
	public static void main(String[] args){
		NullDereference NullDereference = new NullDereference();
		NullDereference.test().trim();
	}
}

class NullDereference{
	private boolean alwaysTrue = true;	
	
	public String test(){
		String data;
		if(alwaysTrue){
			data = null;
		}else{
			data = "hello ";
		}
		
		return data;
	}
}
```
```
Program.java:4: error: NULL_DEREFERENCE (backend/rearrange.ml:1007:57-64:)
  [B1] object returned by noNullDereference.test() could be null and is dereferenced at line 4
  2.   	public static void main(String[] args){
  3.   		NoNullDereference noNullDereference = new NoNullDereference();
  4. > 		noNullDereference.test().trim();
  5.   	}
  6.   }
  7.   
```
-------------
**Example 4: True positive**
```java
  public class Program {
	public static void main(String[] args){
		NoNullDereference noNullDereference = new NoNullDereference();
		noNullDereference.test().trim();
	}
}

class NoNullDereference{
	private boolean alwaysFalse = false;	
	
	public String test(){
		String data;
		if(alwaysFalse){
			data = null;
		}else{
			data = "hello ";
		}
		
		return data;
	}
}
```

```
Analyzed 1 file

  No issues found  

[INFO:infer:146] Capture phase was successful
```

Fix 2: Change the boolean variable with a boolean
-------------
**Example 5:  true positive**
```java
public class Program {
	public static void main(String[] args){
		NoNullDereference noNullDereference = new NoNullDereference();
		noNullDereference.test();
	}
}

 class NoNullDereference{	
	public void test(){
		String data;
		if(false){
			data = null;
		}else{
			data = "hello ";
		}
		
		data.trim();
	}
}
```

```
Analyzed 1 file

  No issues found  

[INFO:infer:146] Capture phase was successful
```

------------
**Example 6: true positive**
```java
public class Program {
	public static void main(String[] args){
		NullDereference nullDereference = new nullDereference();
		nullDereference.test();
	}
}

 class NoNullDereference{	
	public void test(){
		String data;
		if(true){
			data = null;
		}else{
			data = "hello ";
		}
		
		data.trim();
	}
}
```

```
Program.java:17: error: NULL_DEREFERENCE (backend/rearrange.ml:1007:57-64:)
  [B1] object data last assigned on line 12 could be null and is dereferenced at line 17
  15.   		}
  16.   		
  17. > 		data.trim();
  18.   	}
  19.   }
```

**Comment by jvillard** [comment]
Thanks for the detailed question, @wouter89. What you are seeing is because infer doesn't do a global analysis of a class (in this case `NoNullDereference`) to figure out invariants (in this case "`alwaysFalse` is always `false`"). To explain, let me try and go over your tests:

1. Infer analyses `test()` on its own (without looking at the context) and finds that it could dereference `null` if `alwaysFalse` is `true`. Since infer doesn't try to analyse the context of the method, only the method itself, it doesn't know that `alwaysFalse` cannot in fact be `true`. The analysis of `main()` shows no error.

2. Same as 1, except this time it turns out that `alwaysTrue` can indeed be `true` to this report turns out to be legit.

3. Infer analyses `test()` and finds no issue. It stores 2 specifications about `test()`: A) when `alwaysTrue` is `true` then the return value is `null`; B) otherwise it is `"hello"`. Infer then analyses `main()`. At the point where `main()` calls `test()`, the value of `nullDereference.alwaysTrue` is `true`, so infer uses specification A and then finds an error when simulating the execution of `null.trim()`.

4. Similar to 3, except than at the point where `main()` calls `test()` infer selects specification B and doesn't find any error when symbolically executing `"hello".trim()`.

5. Infer analyses `test()` and finds no error because it knows which branch to take in `if (false) ...`.

6. Same as 5 and Infer correctly finds the NPE.

I hope this answers your question. Feel free to open another issue about the general fact that infer doesn't try to find out which fields never change before anaylisng the methods in a class.

**Comment by wouter89** [comment]
Thanks for the explanation, very clear! 

Is there a similar limitation when working with classes in C++? I've  found the following example which I could not explain just by looking at the results from Infer. In this case Infer does report the NULL_DEREFERENCE  in the method that isn't in the class (even though the method in the class in the same).

```C
#include <stdlib.h>
#include <string.h>

class A
{
	public: void test()
	{
		char * data;
		data = NULL;
		strcpy(data, "Initialize");
	}
};

void test()
{
	char * data;
	data = NULL;
	strcpy(data, "Initialize");
}

int main()
{
	A a;
	a.test();
	test();
    return 0;
}
```

**Comment by jvillard** [comment]
c++ analysis is still experimental and unsupported for now. Infer doesn't analyse c++ code by default, so won't report on `A::test()`. You can pass `--cxx` to switch the experimental c++ analysis on (you may need to upgrade to the current git version of infer first).
