### ISSUE TITLE
Precondition_not_met for array functions [Question]

### ISSUE THREAD

**Issue by wouter89** [facebook/infer#379]
I've analysed the following code snippet with Infer:

``` java
void update(int i, int val){
    a[i] = val;
}
```

Where 'a' is an already initialised array of integers. When I analysed the class that calls this function I saw that Infer's debug information in the captured folder outputs: 'precondition_not_met in call to update..' 

This warning can be removed by changing the function update to something like this:

``` java
void update(int i, int val){
   if(i < a.length || i < 0) return;
   a[i] = val;
}
```

Which makes sense because if I look at the preconditions for the function update it requires that 'i', 'val' and 'this' point to allocated memory (and if I interpreted the output correctly) that 'this' has an object 'val$[number]' which is reachable from 'this' and represents the value 'a[i]'. 

If I would (try to) write it in separation logic, something like this: 

```
{ i |-> _ * val |-> _ * this.a |-> j * ls(j,i') * i' |-> _  }   

update(i, val)   

{ i |-> _ * val |-> _ * this.a |-> j * ls(j,i') * i' |-> val }
```
1. There doesn't seem to be a relation between i and i' in the pre and postcondition, how does Infer infer this?
2. Can I draw the conclusion from this that Infer 'knows' about the array bounds, and finds that without the added check for the function update 'a[i]' may not be reachable?
3. The length of 'a' doesn't seem to matter, I believe because Infer applies an abstraction for loops and assumes that after a couple of correct loops it will work on loops for arbitrary size, or is this a wrong assumption and does Infer know something about the exact size of array's and lists?

Debug output:
(BigObject contains the array 'a' )

```
PRE:
val = val$1 formal:int ( sub ) ; 
this = val$2 formal:class small.BigObject *( sub ) ; 
i = val$5 formal:int ( sub ) ;
this|->{small.BigObject.a:val$3 rearrange:(z)14} rearrange:(z)14:class small.BigObject ( sub ) ; 
val$3|->[val$4|i:val$6 rearrange:(z)14] rearrange:(z)14:int [val$4]( sub )
POST 1 of 1:
val = val$1 formal:int ( sub ) ; 
this = val$2 formal:class small.BigObject *( sub ) ; 
return = val$7 initial:void  ; 
i = val$5 formal:int ( sub ) ;
this|->{small.BigObject.a:val$3 formal(z)} formal(z):class small.BigObject ( sub ) ; 
val$3|->[val$4|i:val update:(z)14] formal(z):int [val$4]( sub )
```

**Comment by sblackshear** [comment]
Sorry to be so slow in answering your questions!

(1) I don't fully understand this. The precondition `{ i |-> _ * val |-> _ * this.a |-> j * ls(j,i') * i' |-> _  }` is one that you wrote by hand, not one that Infer produced, right? Infer doesn't introduce inductive `ls` predicates for arrays, so it has no notion of an `i'`.

(2) Yes, Infer knows to add proof obligations for array bounds, and this is indeed what results in the `PRECONDITION_NOT_MET`. Although Infer can report some basic array bounds errors (check out `ArrayIndexOutOfBoundsExceptionExample` in the tests), these errors are not reported by default because they tend to bit a bit noisy. You can ask Infer to report them by running with the `-nf` flag.

Even though these errors are off by default, Infer can run into situations where it encounters a `PRECONDITION_NOT_MET`. This means that the caller cannot satisfy the precondition for its callee, but it also doesn't know what the consequences of not satisfying the precondition are--will it result in an out of bounds access, a null dereference, or was the inferred precondition just not general enough?

(3) Infer only knows about the exact size of arrays, and even then only if the size of the array is a constant. In other cases, Infer does indeed apply abstraction in loops to compute pre/postconditions that are independent of the size of an array/list.

Hope this helps, am happy to clarify or answer more questions!
