### ISSUE TITLE
infer too slow

### ISSUE THREAD

**Issue by fancygeek** [facebook/infer#390]
it has cost me an hour to analyse my ios app,not done yet.how to make it quick

**Comment by jvillard** [comment]
How long does it take to compile your project?

It's expected that analysing a whole project can take some time, but there may be something wrong if running Infer takes a lot longer than compiling your project. What is the command you use to run Infer and which version of Infer are you using?

If you're only interested in analysing some changes (eg introduced by a commit), have a look at the [differential workflow](http://fbinfer.com/docs/infer-workflow.html#differential-workflow) which does not run a full analysis.

**Comment by fancygeek** [comment]
i use the this command : infer -- xcodebuild -workspace HelloWorld.xcworkspace -scheme HelloWorld
Infer version v0.8.1

**Comment by jvillard** [comment]
How long does it take to compile your project?

**Comment by fancygeek** [comment]
about 2 or 3 mins to compile my project.my project is about 50m in app store.if my project use cocopos,will infer analysis all dependices or just my framework.

**Comment by boyue** [comment]
It cost me 1-2 hours to analyze my android project includes 7000+ java files.
How can I improve the speed?

**Comment by sblackshear** [comment]
Are you using the Gradle [plugin](https://github.com/uber-common/infer-plugin) for Infer? This should speed up the analysis quite a bit over the default Gradle integration, especially on a multicore machine.

Another thing you can try is instructing Infer only analyzing the files that have changed since the last analysis: `infer --reactive -- gradle assembleDebug` (assuming you have not blown away the `infer-out` directory from the last Infer run).

**Comment by harshikesh** [comment]
_--changed-files-index_ 
What is the use of this? Is it same as "infer_whitelist ":[ ] and Can you give the full command, because It is giving me error:  Unknown command-line option '--changed-files-index'. 

I am just looking for an options to run infer on a particular file which should be faster than normal in android application.
Thanks.

**Comment by jvillard** [comment]
There have been a number of improvements in infer since this issue was open so I'm closing it. @fancygeek please re-open if infer is still many times slower than compilation.

@harshikesh sorry for the delay; `infer --changed-files-index file_list.txt --reactive ...` will not analyse all the source files that have been captured, but instead only the ones in "file_list.txt", and the ones that they depend on.

**Comment by fancygeek** [comment]
ok，thank you!
