### ISSUE TITLE
NPE check not triggered for getters

### ISSUE THREAD

**Issue by chainani** [facebook/infer#397]
I have a getter in a class that returns an Object. When a function of this object is called (eg. `a.getObject().doSomething();`), infer does not trigger a warning for a possible NullPointerException. Is this the designed behaviour or is this an issue at my end? If this is the designed behaviour, is there a good way of ensuring such things don't pass on to production?

**Comment by jvillard** [comment]
Can you provide a full minimal example that reproduces your issue? Shooting from the hip, you could add a `@Nullable` annotation to the return of your getter method so that Infer assumes it can return null.

More (speculative) details: When Infer doesn't know about a function for whatever reason (no implementation available, or Infer failed to analyse it), Infer will treat that function "angelically" and assume that eg it never returns null. This is done to prevent being too noisy. This may or may not be what's happening in your case, we'd need to see some code to know for sure.

**Comment by jberdine** [comment]
Closing for now, please reopen with more info if this is still an issue with the latest version.
