### ISSUE TITLE
Infer does not report a Null Dereference Issue for concatenation of 2 static Strings in Java

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#414]
I ran infer using `infer -- javac Hello.java` on the file [Hello.java](https://gist.github.com/xennygrimmato/260d50a78be0a21f0c5552d6b80a4ec2), but it found no issues. However, running the code gave me a NullPointerException. Is Infer not supposed to handle such cases? What am I missing?
![image](https://cloud.githubusercontent.com/assets/4271899/17306769/d6379ac0-5842-11e6-8c01-b5816219b170.png)

**Comment by sblackshear** [comment]
Infer will only warn when it sees a `null` value flowing to a dereference either directly, or transitively via a call site. Doing otherwise tends to lead to too much noise.

To see *all* (or almost all) possible NPEs rather than the high-confidence subset that Infer reports, try Eradicate `infer -a eradicate -- <your_build_cmd>`. It will definitely warn on this example.
