### ISSUE TITLE
Participate in Ockham Criteria?

### ISSUE THREAD

**Issue by brotherpaul143** [facebook/infer#427]
We ran the [SATE V Ockham Sound Analysis Criteria](https://samate.nist.gov/SATE5OckhamCriteria.html) to better understand sound analyzers. Would anyone be interested in running Infer for another Ockham? Basically that consists of running an analyzer on a substantial set of code that we select and sending us the results. We'd also appreciate answering questions about details of the results that arise.

-paul-
paul.black@nist.gov

**Comment by jberdine** [comment]
@brotherpaul143 Thanks for your interest in Infer. Perhaps there is some oversight, but as far as we understand Infer does not satisfy the SATE criteria. Infer produces two basic forms of output: 1) specifications of procedures / functions / methods, and 2) issue reports for property violations. Only the inferred specifications are claimed to be sound (subject to some idealistic and optimistic assumptions). Here the notion of sound is that from the logical tradition. In particular, if infer produces {P} f(x) {Q}, then soundness means that execution of f from any state satisfying P does not crash and unless it diverges, the state after f returns satisfies Q. The reports of property violations are produced primarily from failed proofs of such specifications. There is no definition of correctness for these reports, let alone a claim of soundness for them.

**Comment by brotherpaul143** [comment]
The Ockham criteria was established to highlight the strength of analyzers using rigorous inference, in contrast to those that use heuristics. It does not require that all results be absolutely correct (halting problem, after all). Rather, are there some results that are correct? Since Infer results of {P} f(x) {Q} are always correct, given the qualifications you mention, I believe Infer would be consonant with the goals of Ockham.

**Comment by jvillard** [comment]
@brotherpaul143 it seems that Infer and SATE use two opposite definitions of correct/sound. From your website:

"1. The tool is claimed to be sound."

and

"Sound means every finding is correct. The tool need not produce a finding for every site; that is completeness."

This is simply not the case for Infer: reports made by Infer may not correspond to an actual weakness in the code.

Note that Infer is sound in the logical sense, which seems to correspond to your notion of "completeness": if Infer doesn't report on a procedure, then that procedure has no bugs (as @jberdine said, "subject to some idealistic and optimistic assumptions"). Infer reports a bug when it fails to prove that a procedure has no bugs (and when Infer's internal heuristics suggest that it may correspond to a real issue, otherwise Infer would be too noisy), not when it can prove that a procedure definitely has a bug.

**Comment by brotherpaul143** [comment]
I agree with you, @jvillard   Please note that Ockham uses the term "finding". The use of "finding" allows an additional level of interpretation. As you point out, "if Infer doesn't report on a procedure, then that procedure has no bugs". The *lack* of a report is a finding for Ockham's purposes. That is, users can absolutely depend on the fact that no bug reportfrom Infer  means that the procedure is bug-free "subject to some idealistic and optimistic assumptions", as @jberdine said.

Infer is welcome to participate in Ockham.

**Comment by jberdine** [comment]
It is unclear how Infer's "findings" could be evaluated or validated.  For example, suppose that for a function `f` Infer computes a specification `{P} f(x) {Q}`.  If Infer is wrong, how can this be demonstrated?  It seems that it would finding a state that satisfies `P` from which executing `f(x)`, subject to Infer's idealistic and optimistic assumptions, either crashes or returns in a state that does not satisfy `Q`.  No mechanized way of doing this is known.  Do you have something else in mind?

**Comment by brotherpaul143** [comment]
@jberdine asks, "Do you have something else in mind?" Yes. There are lots of steps and checks and details and caveats and conditions, but the basic outline is as follows. We choose a test suite with known bugs. If Infer fails to report a bug, then it doesn't satisfy the SATE VI Ockham Criteria. 

I appreciate @jberdine and @jvillard responding to my inquiry. I'm a little surprised with what I perceive as the reluctant attitude. I should think the community would be excited to demonstrate the strengths of Infer. Thank you for your time and patience with me.

**Comment by jberdine** [comment]
@brotherpaul143, Thanks for bringing this up, and I don't mean to be off-putting.  What you're interpreting as reluctance is more wariness, and the expectation that the reality of how gray questions of soundness and completeness are for tools like Infer undermines the viability of these sorts of exercises.  In particular, Infer uses both sound techniques and heuristics which are neither sound nor complete.  Additionally, Infer uses the classical logical notion of soundness, which seems to correspond more to what you term completeness.  Infer does not do any reasoning that fits what you term "soundness".  The other difficulty is that the logically robust reasoning that Infer does produces specifications that are used internally by Infer, but not directly reported to developers.  Evaluating the correctness of these specifications is nontrivial, since they are hypothetical statements with very involved premisses.

**Comment by cristianoc** [comment]
@brotherpaul143 I think a good summary is that Infer comes from sound design principles, makes unsound compromises and heuristics where it makes sense. In particular, Infer tries to maximize the value given to developers, over soundness or completeness concerns.

Now that all the provisos are out of the way, the main question is whether, given these provisos, you think that the results will be useful for SATE V. I guess this is for you to assess.

**Comment by cristianoc** [comment]
As a side note, I like to split things up in 2 separate aspects: report rate and fix rate.
Report rate measures how many defects that exist, are reported.
Fix rate measures how many reported issues are fixed by developers.

The reason for split things up in this way is that: first, the developer is part of the picture, the source of the value judgement. So the focus is to issue reports that bring value to the developer, as measured by the developer's willingness to act on the reports.
This set-up includes the situation with type checkers, that over-report by definition, but have a perfect fix rate (developers address type errors in order to compile the code).

**Comment by brotherpaul143** [comment]
@cristianoc thanks, I believe I understand now. Infer's approach sounds eminently practical. You're right though: with the heuristics filtering results before they reach the user, Infer is not a candidate for the Ockham criteria track in SATE VI. However, Infer would fit very well in other tracks in SATE VI.

Again, thanks for patiently answering my questions, @jberdine and @jvillard too.
