### ISSUE TITLE
Android: false negative on `if ((list == null) && (list.size() == 0))` ?

### ISSUE THREAD

**Issue by liweijian** [facebook/infer#433]
I wrote a demo to test the capability between Findbugs and Infer.

Here's class `Utilz`:

``` java
public class Utilz {
    public static String mayReturnNull(int i) {
        if (i > 0) {
            return "It's Good!";
        }
        return null;
    }

    public static int lstLen(List list) {
        if ((list == null) && (list.size() == 0)) {
            return 0;
        }

        return list.size();
    }
}
```

Here's the activity:

``` java
public class Findnobugs extends AppCompatActivity {

    TextView tv_show;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_findnobugs);

        Random rng = new Random();
        String txt = Utilz.mayReturnNull(rng.nextInt());
        tv_show = (TextView) findViewById(R.id.tx_show);
        tv_show.setText(String.valueOf(txt.length()));
    }
}
```

Infer could hunt the _NULL_DEREFERENCE_  in

``` java
21.           String txt = Utilz.mayReturnNull(rng.nextInt());
22.           tv_show = (TextView) findViewById(R.id.tx_show);
23. >         tv_show.setText(String.valueOf(txt.length()));
24.
```

And findbugs could hunt the other

``` java
        if ((list == null) && (list.size() == 0)) {
            return 0;
        }
```

**Comment by akotulski** [comment]
Thanks for the report. We'll look into it.
It looks like infer finds out bug in `lstLen` but then it gets filtered out. If you run infer in debug mode (`infer -g ...`), you'll see null dereference in `[B5]` bucket.

**Comment by liweijian** [comment]
Thank you @akotulski ,I was curious why Infer ignore `lstLen` in that case?

**Comment by sblackshear** [comment]
Our filtering heuristics tend to rank reports where an explicit flow of null to a dereference site is observed as high-confidence, and reports where a variable is compared to `null` and then dereferenced (such as the example here) as low-confidence. 

The reason is that reports for the latter reason can often be false positives when the comparison to `null` is in a callee. That said, there are often cases like your example here where the result is pretty high-confidence. We should perhaps try to adjust our heuristics for this case.

**Comment by sblackshear** [comment]
Closing because we do find this even though the default bucketing filters it out.
