### ISSUE TITLE
In terminal build error

### ISSUE THREAD

**Issue by ychexingwuji** [facebook/infer#465]
Use Xcode8 

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSCharacterSet.h:27:22: error: 
      unknown property attribute 'class'
@property (readonly, class, copy) NSCharacterSet *uppercaseLetterCharacterSet;
                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by jvillard** [comment]
Which version of Infer are you using? This may be due to an incompatibility with the version of clang used by Infer up to 0.9.2. See #464.

Please try again using infer from latest master, which includes an updated clang, or wait until we release 0.9.3 (should be soon!) to save you some compilation time.

**Comment by jberdine** [comment]
Infer 0.9.3 has been released, please try and reopen this issue if the problem remains.
