### ISSUE TITLE
Unknown command-line option '--changed-files-index'.

### ISSUE THREAD

**Issue by harshikesh** [facebook/infer#527]
I am using this command
infer -- ./gradlew run --changed-files-index app/src/main/java/com//ui/MainActivity.java

It is giving : Unknown command-line option '--changed-files-index'

**Comment by jvillard** [comment]
This is passing `--changed-files-index` to gradle, not infer. You want to specify it before `--` and give it as argument a file containing a list of source files to reanalyse:

```
$ infer --help
[...]
  --changed-files-index <file>
                         Specify the file containing the list of source files from which
                         reactive analysis should start. Source files should be specified
                         relative to project root or be absolute
[...]
$ cat changed_files.txt
app/src/main/java/com//ui/MainActivity.java
$ infer --changed-files-index changed_files.txt --reactive -- ./gradlew run
[...]
```

This will capture all the files in your project, but analyze only MainActivity.java and the files it depends on.

**Comment by harshikesh** [comment]
Thanks for the answer!
Is --changed-files-index works same as if you run keeping the file name in .inferconfig as whitelist?
 "infer_whitelist": [
     "app/src/main/java/com/ui/MainActivity.java"
   ],

**Comment by harshikesh** [comment]
@jvillard  Can you please reply I am stuck?

**Comment by jvillard** [comment]
The whitelist is so that infer doesn't skip analyzing a file that would otherwise be blacklisted. `--changed-files-index` tells infer where to start the analysis from and makes sure all the files in the index are re-analyzed by infer. Without `--changed-files-index` infer will analyze all the files that were captured (or, if `--reactive` was passed, all the files that infer finds have changed since the last run). The blacklist/whitelist options is another mechanism on top of that; for instance, if a file in the index is blacklisted, it will still not be analyzed.

What are you trying to achieve, what have you tried and where are you stuck?

**Comment by harshikesh** [comment]
Thanks for explaining @jvillard . 

Problem statement :

>  What I am trying to achieve is to run Infer on some files, then re analyse those files after fixing issues. 

First I whitelisted some files on which I want to run infer then,
_I tried all these commands._ 
`infer -- ./gradlew run`  //I was running this each time after fixing my issues It worked but it is taking too much time. 

`infer --reactive -- ./gradlew --offline run` // This gives no issues found each time after first build

`infer --changed-files-index changed_files.txt --reactive -- ./gradlew run` // This gives no issues found. If I don't use --reactive It takes same time as` infer -- ./gradlew run`

I tried 
`-j 16` but It was not of much help because it took same time.

Can you please suggest what should be done to get result faster for specific files.
