### ISSUE TITLE
Error during capture phase on makefile project

### ISSUE THREAD

**Issue by davido** [facebook/infer#545]
I'm trying to run infer v0.9.4 on `LibreOffice` project, and getting this error:

```
[davido@wizball salhelper]$ infer --debug -- make VEBOSE=t
[...]
Nothing to compile. Try running `make clean` first.
[ERROR:infer.py:188] Error during capture phase, exiting
```

The full output can be found here: http://paste.openstack.org/show/593310. Can I get more detailed message on this failure?

**Comment by jvillard** [comment]
C++ is not enabled by default in 0.9.4.1, you need to pass `--cxx` to infer (this will be the default in the next release).

Also, just to make sure: you will need to run `make clean` first:

```
make clean && infer --cxx -- make VERBOSE=t
```

**Comment by davido** [comment]
Doesn't seem to help:

```
$ infer --debug --cxx -- make VERBOSE=t
[...]
Nothing to compile. Try running `make clean` first.
```

And the log file contains:

```
$ cat infer-out/log/top_level/infer_9570_5ff0a3-err.log
Failed to execute: /home/davido/projects/infer-linux64-v0.9.4.1/infer/bin/../lib/python/infer.py --analyzer infer -j 16 --project-root /home/davido/projects/libreoffice/salhelper --out /home/davido/projects/libreoffice/salhelper/infer-out -- make VERBOSE=t
```

**Comment by akotulski** [comment]
I suspect there is something non trivial going on in those Makefiles and infer doesn't deal with it nicely. We replace normal compilation commands with ours and sometimes some file expected by Makefile may not be created/updated.
For example, you are never supposed to run code created by `infer -- make all` invocation. Maybe your `Makefile` does it somewhere?

Is it possible for us to reproduce issue locally in simple steps?

**Comment by jvillard** [comment]
It could also be that infer cannot capture calls to the compiler because the path to the compiler is there with absolute paths in the Makefiles.

Was Makefile generated by some other tool?

**Comment by davido** [comment]
It's hand written make files, but I agree they are not trivial. That why I asked how could I get stack traces and/increase verbosity?

To reproduce, you would need to set up [LibreOffice development environment](https://wiki.documentfoundation.org/Development/BuildingOnLinux), in a nutshell:

```
# install dependencies for your distribution
$ git clone git://anongit.freedesktop.org/libreoffice/core libreoffice
$ cd libreoffice
$ ./autogen.sh
$ make
```

**Comment by jvillard** [comment]
I suspect this is a case of absolute paths to the compilers set by `./configure`, I'm downloading the libreoffice sources to confirm. In the meantime, you can try:

  infer -- ./configure
  infer --cxx -- make

**Comment by jvillard** [comment]
So far, I haven't succeeded in building libreoffice because I got a source tarball from master on the GitHub mirror, which doesn't include sources.ver which is required to build.

However, I did manage to make the build system accept the infer wrappers as compilers by doing:

```lang=sh
$ CC=clang CXX=clang++ CXXFLAGS="-stdlib=libc++" infer -- ./configure --without-doxygen --disable-gtk3 --disable-gtk --disable-gstreamer-1-0
```

The flags I added to `./configure` are just there so that I don't have to install these dependencies; I don't think they are needed to build. The version of stdlibc++ on my system was no good according to libreoffice so I had to force `-stdlib=libc++`.

Now I get `export COMPATH=/home/jul/infer/infer/lib/python/inferlib/../../../lib/wrappers` in config_host.mk, so I have some confidence that this could work:


```lang=sh
$ CC=clang CXX=clang++ CXXFLAGS="-stdlib=libc++" infer -- ./configure --without-doxygen --disable-gtk3 --disable-gtk --disable-gstreamer-1-0
$ infer --cxx -- make
```

**Comment by jvillard** [comment]
> So the problem is that configure phase must be aware of infer analyzer for makefile integration to work?

In this case, yes.

The way infer is integrated with `make` is a simple `PATH` trick that replaces gcc/clang/... with our wrappers that run infer instead. `PATH` has no power when the path to the compiler is used instead of just its name (eg, `/usr/bin/clang` will not lookup `PATH`, so will bypass infer).

Some build systems such as `cmake` and LibreOffice's custom build system defeat this simple mechanism, and `PATH` has to be set earlier, at configuration time, so that the path to the compiler is set to infer: `infer -a compile -- ./configure` or `infer -a compile -- cmake` will do this.

**Comment by davido** [comment]
> The version of stdlibc++ on my system was no good according to libreoffice so I had to force -stdlib=libc++.

I see this too, but only if `infer` is involved. When I use direct `clang/clang++`, then all is fine with libstdc++. I asume this is a bug on `infer` side?

**Comment by davido** [comment]
Found a workaround for `configure` phase: compiled clang from trunk, and used it with `libstdc++` as usual. After configure step, I replaces in config_host.mk `CC`, `CXX` and `COMPATH` with the right value for `infer`. Now after calling `infer --cxx -- make` I am getting this report: [1], mostly complaining about `unique_ptr` redefinition. 

*  [1] http://paste.openstack.org/show/593905/

**Comment by akotulski** [comment]
Those errors are because we have our own simplified headers for `std::unique_ptr` so that analyzer understands it. Unfortunately, in your case those headers conflict with standard ones and we didn't catch it (see below for more info). If you can compile infer from source, you can work around this problem by changing one line in `ClangCommand.re`: https://github.com/facebook/infer/blob/master/infer/src/clang/ClangCommand.re#L32
simply change it to `let infer_cxx_models = false`. It will make analysis worse (no null dereference in `shared_ptr`, `unique_ptr`, no EMPTY_VECTOR_ACCESS from `vector`), but you should be able to run infer.

The reason why you are hitting this problem is because mechanism we model `unique_ptr` is fragile. We 'replace' normal headers with ours by providing another `bits/unique_ptr.h` header which normally works. Unfortunately, there is weird implementation in one of stdlibc++ headers (`bits/locale_conv.h`) which includes `bits/unique_ptr.h` via `#include "unique_ptr.h"` and we can't detect that.
I have plans to change this mechanism, but I suspect it will take a while to complete.

**Comment by davido** [comment]
Another question is would using libc++ also run in the same `unique_ptr` issue, or is this only stdlibc++ specific issue? I'm asking, because on Linux it's not trivial to use libc++. And i wanted to avoid going down that path.

**Comment by akotulski** [comment]
This issue is specific to libstdc++, possibly introduced in versions 6.x (4.9.x are battle tested and work, 5.x seemed to work when I tried).
You are right that it will break anyone that ends up including that header, unfortunately it's not trivial to replace our current mechanism with more robust one.

If we get more reports like this, I'll try to think of better workaround for the problem. The most trivial one for you would be to copy-paste contents of `/path/to/stdc++/include/bits/locale_conv.h` to `infer/models/cpp/include/bits/locale_conv.h` and then replace faulty `#include "unique_ptr.h"` with `#include <bits/unique_ptr.h>` (then you could revert previous workaround I suggested)

**Comment by davido** [comment]
It seems to work, but I had to copy number of other inlcludes.

The next problem I'm running into, in LO we create files, like UNO compiler and then generate classes from type library description. Now these files are instrumented too, and the execution during the make execution now failing with:

```
!!! This program must not be run !!!
This code was compiled to be analyzed by Infer.
To run this program, recompile it without Infer.
```

Am I right in assuming that those tools should be excluded from checks. I tried to add `.inferconfig` file with this content to those subdirectories: http://paste.openstack.org/show/594070 but it seems to be ignored.

**Comment by akotulski** [comment]
At this point I can tell that this is one of the more complex open source projects I've seen so far :)

The problem with infer's current mechanism is that we replace std headers with different ones which are not equivalent (`shared_ptr` is not refcounted for example) and hence we explicitly disallow to run binaries that were created with our headers. In your case, it looks like that you
1. create a tool X to do something with code
2. run X to produce something
3. use results of (2) as source for compilation (?)

To fix this, I see two options:
Option one:
I assume you have target in `make` that does only (3) and there is target that does (1) and (2)
```
infer -a compile -- ./configure
infer -a compile -- make steps_1_and_2
infer --cxx -- make step_3 # analyze source code of your project

OR
infer --cxx -- make step_1 # to analyze source code of tool X
```

Option two:
Similar to what your tried to achieve in last comment - you can try to exclude directories that are responsible for tools created in (1). Create `.inferconfig` file in project root directory (which by default is the directory you run infer from) and specify parameter called `skip-clang-analysis-in-path` with paths relative to project root directory (it can be path to directory, not separate files).

Both of those options should hit [the same code path in infer](https://github.com/facebook/infer/blob/master/infer/src/clang/Capture.re#L161) and simply compile tool X.

**Comment by davido** [comment]
Thanks, it works: [1] in the end ;-)

* [1] http://paste.openstack.org/show/594146
