### ISSUE TITLE
Question: Multicore mode

### ISSUE THREAD

**Issue by rvantonder** [facebook/infer#569]
How does Infer partition files for analysis in multicore mode (and how does this relate to cluster makefiles)?

**Comment by jvillard** [comment]
The partition is that each file is one cluster. The makefiles run the clusters in parallel.

Clusters (and Makefiles) exist mainly because of historical reasons: it used to be the case that infer partitioned procedures according to a call graph that it was trying to compute before the analysis. Now we rely on an on-demand analysis of procedures: if the analysis of a procedure `foo` requires the spec of a procedure `goo` (because `foo` calls `goo`, for instance) and `goo` has not been analysed yet (it has no spec), then it schedules the analysis of `goo`.

**Comment by rvantonder** [comment]
Thank you @jvillard, that's helpful.
