### ISSUE TITLE
Support for android.util.Pair

### ISSUE THREAD

**Issue by trulex** [facebook/infer#571]
CLASS_CAST_EXCEPTION is reported for code where Pair is used and running Infer in debug mode.
```
Pair<Integer, Integer> pair = getPair();
Integer groupIndex = pair.first;
```
error: CLASS_CAST_EXCEPTION (backend/BuiltinDefn.ml:249:10-17:)
  class android.util.Pair cannot be cast to class java.lang.Integer   at line 20

**Comment by jeremydubreil** [comment]
There currently are issues with `CLASS_CAST_EXCEPTION`. These warnings are not production ready so you should not rely on those warnings. The issue here is not specific to `android.util.Pair` but more broadly about having parse data when checking for sub-typing. This is being worked on so this particular issue may disappear once class cast checks are production ready.

Please re-open an issue if you still get the same error once Infer starts reporting class cast exceptions by default.

**Comment by trulex** [comment]
Thank you.
