### ISSUE TITLE
How to build linux kernel with infer

### ISSUE THREAD

**Issue by banfeng** [facebook/infer#580]
Hi all,

Recently I would like to use infer to check the linux kernel v3.18 sourcecode.
For example, I can successfully use infer to check the files which locate in .../examples/.
However, if changing to kernel driver, such as .../driver/mmc/core/core.c, it will meet lots of header files doesn't include.
And if following aosp build kernel steps, http://source.android.com/source/building-kernels.html,
it seems lots of "error, forbidden warning" will occur.

Does anyone has any experimence in building kernel sourcecode can share with me?! Appreciate that.

**Comment by akotulski** [comment]
In general, in order to to analyze code with infer, you need working compilation command and most of the time we can't tell our users what the right command is.

With your example, let's say you want to analyze `../driver/mmc/core/core.c`:
you probably can't run `infer -- clang -c ../driver/mmc/core/core.c`, as it will miss header search paths. Instead, you need to find Makefile target that builds that file. 

As for analyzing linux kernel - normally kernel compiles only with gcc. Infer uses clang compiler and linux kernel probably won't compile with clang without changing linux source code. It's outside of scope of our project to do that though.

Complex makefile projects may require more work to work with `infer`, but we can help with that if we have compilation that works without `infer`. See `libreoffice` as an example:
https://github.com/facebook/infer/issues/545

**Comment by jvillard** [comment]
Please reopen with more details if needed. In particular, please include the commands you have tried to run infer on Linux.
