### ISSUE TITLE
Is @SuppressWarnings("infer") not supported from 0.9.4 ??

### ISSUE THREAD

**Issue by mohammedsafiq** [facebook/infer#591]
But the documentation says it is removed in 0.10.0. Then how come it is not working in 0.9.4 itself?

**Comment by mohammedsafiq** [comment]
But the documentation says it is removed in 0.10.0. Then how come it is not working in 0.9.4 itself?

**Comment by jeremydubreil** [comment]
Do you have a small example where `@SuppressWarnings` does not work with 0.9.4 ?

Having support for `@SuppressWarnings` is very tricky because the default `@SuppressWarnings` annotation only source retention only, and Infer runs on bytecode. The support was based on some complex annotation processing step and I would not be surprised if there are cases where it does not work properly. As of 0.10.0, using `@SuppressLint` should be more stable as we are sure that we can retrieve the annotation from the bytecode.

**Comment by jvillard** [comment]
Please reopen with more information.
