### ISSUE TITLE
Is there a way to run the complete project with single infer command

### ISSUE THREAD

**Issue by shreyasmrs** [facebook/infer#613]
I want to run a scan on all the java files in my root directory. Is there a way to run it in single command something like infer -- javac <folder path>

**Comment by mohammedsafiq** [comment]
It will run for entire project only. try with your build variant.

infer --reactive -- ./gradlew <buildVariant>

**Comment by shreyasmrs** [comment]
for a java project. Not for the android project

**Comment by mohammedsafiq** [comment]
What is the current command you are using?

**Comment by shreyasmrs** [comment]
infer -- javac <folder>/file.java

I want to know a command like infer -- javac  <folder>

**Comment by mohammedsafiq** [comment]
Add this in your command.

-pr "specific module/package/project path for infer to run".

-pr is project root. But your terminal path should be in android root only. Because all supporting files(python files) which helps to run infer will be available in android root. But you can specify your module for infer to run using -pr

**Comment by shreyasmrs** [comment]
thank you
