### ISSUE TITLE
running `make test` fails

### ISSUE THREAD

**Issue by jsachs** [facebook/infer#634]
Running `./build-infer.sh java` runs with no issues, but `make test` yields several errors, all with the following form:

```
g -O2 -stdlib=libc++ -std=c++11 -g -I/Users/Jacob/Documents/dev/infer/facebook-clang-plugins/clang/install/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -fno-common -Woverloaded-virtual -Wcast-qual -fno-strict-aliasing -pedantic -Wno-long-long -Wall -W -Wno-unused-parameter -Wwrite-strings -Wno-uninitialized  -Wno-missing-field-initializers -Wno-vla-extension -Wno-c99-extensions -O3 -DNDEBUG -c SimplePluginASTAction.cpp -o build/SimplePluginASTAction.o
bash: g: command not found
make[1]: [build/SimplePluginASTAction.o] Error 127 (ignored)
```

It looks like `clang -` is not being prepended to these commands, causing them to fail.

I am building Infer 0.10.0 on Mac OS 10.12.3

**Comment by jvillard** [comment]
At the moment `make test` fails if you're building infer for Java only. This is because the [Makefile](https://github.com/facebook/infer/blob/21af28619f3baa970d9c271f590b08ebe090e898/Makefile#L16) does not exclude some tests that depend on the clang parts of infer, even though it should. Right now it tries to exclude them but the logic is incomplete.

We're working on adding this workflow to our CI so that we can fix it without having it regress soon after, but in the meantime the easiest solution is to build infer with the clang analysers enabled if you plan on  running the tests.
