### ISSUE TITLE
"Unavailable api in supported ios sdk" lint doesn't seem to work

### ISSUE THREAD

**Issue by michaeleisel** [facebook/infer#684]
When I try `infer run --iphoneos-target-sdk-version 9.0 --compilation-database compile_commands.json` with this compile_commands.json: https://gist.github.com/michaeleisel/f10252425ff80d33494b92dbd5878ba7 and this file: https://gist.github.com/michaeleisel/3b732f6a0e89713daab4464a873d0f28, the method -unsupportedAPI at line 47 should have problems because AVPlayerLooper is 10.0+, but it doesn't. My infer version is 0.12.0. Any ideas what might be wrong?

**Comment by dulmarod** [comment]
Thanks for reporting, I'll look into it.

**Comment by dulmarod** [comment]
I looked into it, and indeed we don't find that issue. This is because we don't look into attributes of classes as the moment, only on attributes of properties or methods. Question, do you think we should flag any uses of such types or just when an object of that type gets allocated? 
Thanks a lot for your report, it will allow us to improve the checker.

**Comment by michaeleisel** [comment]
I think it'd be OK just to have the type floating around. My one concern though is that we're calling -alloc and initWithPlayer:... on it, wouldn't those cause a crash?

**Comment by dulmarod** [comment]
Yes, they would. I just hadn't taken that case into account in the check. I'm not iOS developer myself.
________________________________

**Comment by dulmarod** [comment]
This is now done in the latest master.
