### ISSUE TITLE
no_polymorphic_compare

### ISSUE THREAD

**Issue by AnyMarvel** [facebook/infer#737]
[*ERROR**][30588] File "/home/AnyMarvel/infer/infer/src/backend/jsonbug_j.ml", line 94, characters 19-42:

[*ERROR**][30588] Error: This expression has type char but an expression was expected of type
[*ERROR**][30588]          [ `no_polymorphic_compare ]
[*ERROR**][30588] make[1]: *** [_build/default/infer.exe] Error 1

Makefile:152: recipe for target 'src_build' failed
make: *** [src_build] Error 1

**Comment by jvillard** [comment]
Try `git clean -fd infer/src/`.

Longer explanation: I suspect that you built infer from git some time before c16884b97fd0a751d6aceb4e9151dfe005d3eafb, when we used to generate jsonbug_j.ml and other files in infer/src/backend/ and had special rules to compile these files with different flags. After c16884b97fd0a751d6aceb4e9151dfe005d3eafb, we generate such files in infer/src/atd. Git will not delete the previously generated files from infer/src/backend/ for you when you update, and since we now compile all the files in that directory with the same flags, compilation fails. The remedy is simply to delete the previously generated files.

**Comment by jvillard** [comment]
Closing optimistically. Please reopen if there's still an issue.
