### ISSUE TITLE
 ./build-infer.sh failed on Linux Mint 18.1 Cinnamon 64bits

### ISSUE THREAD

**Issue by aurimrv** [facebook/infer#741]
Dear all, I am trying to compile Infer on my Linux Mint 18.1 - 64 bits machine but I could not get the executable til now.

I need Infer for C language. I have already try to run ./build-infer.sh all, ./build-infer.sh, and ./build-infer.sh cmake without any success.

The compilation process took a very long time (more than 4 hours) and stuck around 97% with some error messages. Is there another way to install Infer on Linux Mint/Ubuntu distro?

It follows below the final part of the compilation process that I need to interrupt by typing CTRL+C because the machine was very slow for more than hours.

*******************************
Scanning dependencies of target llvm-ar
make[3]: Leaving directory '/home/auri/tmp/clang-setup.LJFpDj/build'
make[3]: Entering directory '/home/auri/tmp/clang-setup.LJFpDj/build'
[ 97%] Building CXX object tools/llvm-ar/CMakeFiles/llvm-ar.dir/llvm-ar.cpp.o
collect2: fatal error: ld terminated with signal 9 [Morto]
compilation terminated.
tools/opt/CMakeFiles/opt.dir/build.make:421: recipe for target 'bin/opt' failed
make[3]: *** [bin/opt] Error 1
make[3]: *** A apagar ficheiro 'bin/opt'
make[3]: Leaving directory '/home/auri/tmp/clang-setup.LJFpDj/build'
CMakeFiles/Makefile2:58617: recipe for target 'tools/opt/CMakeFiles/opt.dir/all' failed
make[2]: *** [tools/opt/CMakeFiles/opt.dir/all] Error 2
make[2]: ** Esperando que outros processos terminem.
[ 97%] Linking CXX executable ../../bin/llvm-ar
make[3]: Leaving directory '/home/auri/tmp/clang-setup.LJFpDj/build'
[ 97%] Built target llvm-ar
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^Cmake[3]: *** A apagar ficheiro 'bin/llvm-lto2'
make[3]: *** A apagar ficheiro 'bin/llc'
make[3]: *** A apagar ficheiro 'lib/libLTO.so.5.0.0svn'
make[3]: *** A apagar ficheiro 'bin/llvm-dsymutil'
Makefile:198: recipe for target 'clang_setup' failed
make[3]: *** A apagar ficheiro 'bin/llvm-dwp'
make: *** [clang_setup] Interrupção
make[3]: *** A apagar ficheiro 'bin/llvm-c-test'

tools/lto/CMakeFiles/LTO.dir/build.make:283: recipe for target 'lib/libLTO.so.5.0.0svn' failed
make[3]: *** [lib/libLTO.so.5.0.0svn] Interrupção
auri@amrv:~/infer$ tools/llvm-lto2/CMakeFiles/llvm-lto2.dir/build.make:257: recipe for target 'bin/llvm-lto2' failed
tools/llc/CMakeFiles/llc.dir/build.make:259: recipe for target 'bin/llc' failed
tools/llvm-c-test/CMakeFiles/llvm-c-test.dir/build.make:540: recipe for target 'bin/llvm-c-test' failed
CMakeFiles/Makefile2:25399: recipe for target 'tools/lto/CMakeFiles/LTO.dir/all' failed
make[3]: *** [bin/llvm-c-test] Interrupção
make[3]: *** [bin/llvm-lto2] Interrupção
tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/build.make:279: recipe for target 'bin/llvm-dwp' failed
make[3]: *** [bin/llc] Interrupção
tools/dsymutil/CMakeFiles/llvm-dsymutil.dir/build.make:383: recipe for target 'bin/llvm-dsymutil' failed
make[3]: *** [bin/llvm-dsymutil] Interrupção
make[3]: *** [bin/llvm-dwp] Interrupção
make[2]: *** [tools/lto/CMakeFiles/LTO.dir/all] Interrupção
Makefile:149: recipe for target 'all' failed
make[1]: *** [all] Interrupção
*******************************

Due to space limitation, I put the complete compilation log and machine info on the link below. Please, if someone could help me I appreciate. All the best

Compilation Error
https://www.dropbox.com/s/4y8jqkcxbx1u2ai/compilation-error-infer.txt?dl=0

System Info
https://www.dropbox.com/s/6h925y9qthnqvgt/system-info.txt?dl=0

**Comment by jvillard** [comment]
The error happens during the compilation of clang. It's expected that compiling clang is slow and resource intensive. You can avoid compiling clang by starting from [our release](https://github.com/facebook/infer/releases/latest), which contain the sources of infer and a pre-compiled clang.

Otherwise, if you want to compile infer from git, you can try reducing the parallelism in the clang build. From the specs of your machine, you have 8 cores and 8GB of memory, probably the later stages of compiling clang are running out of memory because they run on all cores, and they start swapping which is horribly slow.

To reduce parallelism, you have to manually change [this line](https://github.com/facebook/facebook-clang-plugins/blob/ea5e6c489aff5924f0fdeeb1270ee4a878492c8f/clang/setup.sh#L132) in facebook-clang-plugins/clang/setup.sh to hardcode a smaller value, eg
```Bash
JOBS=3
```

Hopefully that stops the compilation of clang from killing your machine.

**Comment by aurimrv** [comment]
The release version with pre-compiled clang solve my problem. Thank you for your help.
Cheers
