### ISSUE TITLE
Unix.Unix_error "Illegal seek" sysconf 

### ISSUE THREAD

**Issue by mfusaro** [facebook/infer#776]
While running ./build-infer.sh on Ubuntu 17.10 there is a compilation failure claiming an uncaught exception. It looks like this is a known issue with [core](https://github.com/janestreet/core/issues/95) but figured I'd log one here for you guys anyway.

`config.status: creating Makefile.autoconf
[14:16:28][22514] Generating source dependencies...
[      1s][22514] SUCCESS Generating source dependencies
[14:16:29][22664] Building native(opt) Infer...
[    208s][22664] SUCCESS Building native(opt) Infer
Uncaught exception:
  
  (Unix.Unix_error "Illegal seek" sysconf "")

Raised by primitive operation at file "src/core_unix.ml", line 348, characters 14-29
Uncaught exception:
  
  (Unix.Unix_error "Illegal seek" sysconf "")
`

**Comment by jvillard** [comment]
Thanks for flagging this. We're monitoring this and will update infer to use the new version of core that fixes it when it becomes available.

**Comment by mfusaro** [comment]
No problem. Ping me if you need more info about the dev environment.

**Comment by 9whirls** [comment]
+1

**Comment by remy-luisant** [comment]
It appears that a new version of core is out.

**Comment by jvillard** [comment]
Thanks for the heads up. Waiting for https://github.com/ocaml/opam-repository/pull/10591

**Comment by avsm** [comment]
now merged into opam!

**Comment by jvillard** [comment]
The new Core release 4.06.0-only, so we cannot upgrade at the moment. It's also unclear to me from [this discussion](https://github.com/janestreet/core/issues/95) if v0.9.2 fixes the issue.

**Comment by Josehc2004** [comment]
Facing same issue, when we can expect the fix for this issue.

onfigure: creating ./config.status
config.status: creating Makefile.autoconf
[11:27:12][10189] Generating source dependencies...
[      0s][10189] SUCCESS Generating source dependencies
[11:27:12][10305] Building native(opt) Infer...
[      1s][10305] SUCCESS Building native(opt) Infer
Uncaught exception:
  
  (Unix.Unix_error "Illegal seek" sysconf "")

Raised by primitive operation at file "src/core_unix.ml", line 348, characters 14-29
Makefile:189: recipe for target '/home/test/infer/infer/man/man1/infer-analyze.1' failed
make: *** [/home/test/infer/infer/man/man1/infer-analyze.1] Error 2
make: *** Waiting for unfinished jobs....
Uncaught exception:
  
  (Unix.Unix_error "Illegal seek" sysconf "")

Raised by primitive operation at file "src/core_unix.ml", line 348, characters 14-29
Makefile:189: recipe for target '/home/test/infer/infer/man/man1/infer-capture.1' failed
make: *** [/home/test/infer/infer/man/man1/infer-capture.1] Error 2
Uncaught exception:
  
  (Unix.Unix_error "Illegal seek" sysconf "")

Raised by primitive operation at file "src/core_unix.ml", line 348, characters 14-29
Uncaught exception:
  
  (Unix.Unix_error "Illegal seek" sysconf "")

Raised by primitive operation at file "src/core_unix.ml", line 348, characters 14-29
Makefile:189: recipe for target '/home/test/infer/infer/man/man1/infer-explore.1' failed
make: *** [/home/test/infer/infer/man/man1/infer-explore.1] Error 2
Makefile:189: recipe for target '/home/test/infer/infer/man/man1/infer-compile.1' failed
make: *** [/home/test/infer/infer/man/man1/infer-compile.1] Error 2

  compilation failure; you can try running

    make clean
    ./build-infer.sh java

**Comment by jvillard** [comment]
Status: currently waiting for https://github.com/janestreet/core/issues/99.

**Comment by remy-luisant** [comment]
I ran some attempts with building infer using the 05 and 06 switches.

Seems like all the relevant janestreet libraries are building for 06 right now, but sawja and parmap aren't working with the 06 switch, so I never got to even run anything.

The 05 switch can complete a build of dependencies, but it still has issues with the illegal seek bug.

Sigh.

**Comment by AnyMarvel** [comment]
I have the same problem. Is this problem solved?

**Comment by remy-luisant** [comment]
Seems like core has closed their bug.

**Comment by jvillard** [comment]
Closing optimistically. Please re-open if upgrading to infer 0.14.0 doesn't solve the issue.
