### ISSUE TITLE
Differential workflow with Buck + dependencies

### ISSUE THREAD

**Issue by varun531** [facebook/infer#898]
Suppose I have an iOS Buck project (Obj-C files), with the following dependency graph:

**AppModule** --(depends on)--> **Dependency1** --(depends on)--> **Dependency2**

and **AppModule** is a top-level target, i.e. building it produces a _.app_ bundle.

If I push a change to CI that modifies **Dependency2** (I add a new Objective-c .m file to it), does running `infer capture -- buck build AppModule` collect the compile commands for the added file in **Dependency2**? Or do I need to explicitly run `infer capture -- buck build Dependency2`?

More generally, with Buck, if I make changes in my project that create the need for new compile commands to be stored in `infer` (I add new source files to a module), or to _update_ the compile commands stored in `infer` (I make a source file in one module dependent on a source file in another module), do I have to explicitly (by name), build the modified modules in buck so that `infer` can capture the required compile commands, or can I just build the top-level module (like an app) that either directly, or transitively, uses the modified modules, and have `infer` capture the relevant compile commands that way?

I would also love some insight as to how Facebook itself uses `infer` with `buck`, for understanding of best practices. For example, how would you handle the above case from commit to commit? And do you prefer to work with compilation databases, or buck output for harvesting compile commands?

Any help is much appreciated!

**Comment by jvillard** [comment]
`infer capture` in general will "see" everything that the compilation command recompiles. In your scenario, since **Dependency2** has chnaged, `buck build AppModule` should rebuild all the targets, since they all depend on **Dependency2**, and infer will capture the compilation of all the source files.

> More generally, with Buck, ...

As above, capturing a target will capture everything that gets built by Buck, so if you are building the whole app it will in particular build your target.

Note that Buck maintains a cache in buck-out/. Everything I've said above relies on the fact that you are doing a "clean" build, i.e. first removing buck-out/.

> I would also love some insight as to how Facebook itself uses infer with buck, for understanding of best practices. For example, how would you handle the above case from commit to commit?

Our integration works by running infer on the top commit, then removing buck-out/ and running infer on the base commit, then comparing the results with `infer-reportdiff`. We still benefit from Buck's distributed cache to get fast incremental results, as most of what we need to analyse will already be in cache.

> And do you prefer to work with compilation databases, or buck output for harvesting compile commands?

We rely on the Buck integration (`infer -- buck build target`) to run all the analyses of infer, so that we benefit from Buck's distributed cache, except the clang linters for which we work with compilation databases (because they're fast enough to run without the Buck cache).

**Comment by varun531** [comment]
@jvillard Thanks so much, that really cleared things up, especially this part:

> Our integration works by running infer on the top commit, then removing buck-out/ and running infer on the base commit, then comparing the results with infer-reportdiff. We still benefit from Buck's distributed cache to get fast incremental results, as most of what we need to analyse will already be in cache.
