### ISSUE TITLE
The `--compilation-database` option is too strict in its parsing of compilation database paths

### ISSUE THREAD

**Issue by TomMD** [facebook/infer#911]
The only "specification" of a compilation database [1] says clearly the path in the `file` field can be relative to the directory from the `directory` field, but infer complains about relative paths.  It seems trivial to make a pass converting the `file` field to an absolute directory.  Would that be an acceptable solution?

Second, there is no word on if the `directory` field must be absolute or can be relative from, presumably, the directory in which the tool was originally invoked.  From my standpoint it would be handy to make this able to be relative as well and rewrite the internal structure as suggested after parsing.

[1] https://clang.llvm.org/docs/JSONCompilationDatabase.html

**Comment by jvillard** [comment]
From [this piece of code](https://github.com/facebook/infer/blob/58f37cb9d80b7e4086fc19e534fd9d2b70688af0/infer/src/integration/CompilationDatabase.ml#L132-L133), infer should only complains if `file` and `directory` are both relative, not just if `file` is relative, right?

I think it makes sense to accept relative directories. What do you think should be used as the root? I think whatever `--project-root` is passed to infer (which defaults to the current directory) would make sense, would that work for your use case? Another option could be to use the directory containing the compile_commands.json file. On top of either of these defaults, there could/probably should be an option to force a root directory for the compilation database anyway.

**Comment by TomMD** [comment]
> infer should only complains if file and directory are both relative

Indeed, something else in my test must have failed and I mis-diagnosed.

> I think it makes sense to accept relative directories. What do you think should be used as the root? I think whatever --project-root is passed to infer (which defaults to the current directory) would make sense, would that work for your use case?

Yes, that makes lots of sense to me.

> Another option could be to use the directory containing the compile_commands.json file.

As a convenience/fallback if there is no `--project-root` this would be handy.  Do we have agreement?  Do you have the time and motivation for these changes?  If not, would a pull request be acceptable?

**Comment by jvillard** [comment]
@TomMD A pull request would be most welcome. Note that that `Config.project_root` is never *not* set as it defaults to the current directory, so we have to choose between using the project root *or* the directory containing compile_commands.json. I don't think it matters to much which one we end up with, so a reasonable command-line interface would be to:

1. Add a `--compilation-database-root` optional flag to infer (using `CommandLineOption.mk_path_opt`, see other options in base/Config.ml).
2. In integration/CompilationDatabase.ml, in case of relative paths use `Config.compilation_database_root` if set, otherwise `Config.project_root`, otherwise bail and ask the user to specify `--compilation-database-root`.

**Comment by TomMD** [comment]
I'm closing this wish-list style item since there are obvious solutions by adjusting use-case or pre-processing.
