### ISSUE TITLE
Context memory leak android

### ISSUE THREAD

**Issue by tregua87** [facebook/infer#982]
Dear all,

I am playing with infer to find some context memory leaks in Android applications  (http://fbinfer.com/docs/infer-bug-types.html#CONTEXT_LEAK).

I wrote a simple PoF to see whether I can spot a context leak:

```
public class MainActivity extends ActionBarActivity {

    public static Context a = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ...
        MainActivity.a = this;
        ...
    }
}
```

As far as I understood, the public static field `a` should leak a context since it points to an Activity instance (see onCreate method). 

However, after running an analysis with infer. I do not find any context leak issues.

I run this command:
```
./gradlew clean
infer run -- ./gradlew build
```

Maybe I forgot to configure infer, and it does not look for context leaks.
Or else my example is wrong as well.

May someone help me with this analysis, please? It would be very appreciated.

Cheers,

**Comment by jvillard** [comment]
Hi @tregua87, the documentation is not up to date as we've actually removed support for context leaks in January: 80b3d080ceb73e20b05967ac16db7459b80b26a7

The issue was that it was reporting too many false positives due to infer not understanding the Android lifecycle: the checker tries to disallow creating persistent references to contexts, but people typically create such references and that's fine provided they get cleanup up in `onDestroy` or similar. This is a bit of a fundamental problem since infer doesn't have any infrastructure for computing class invariants or anything as global as the Android lifecycle.

**Comment by tregua87** [comment]
Hi @jvillard,
really thank you for your reply.

Now I understand! :) sorry for the spam.

From my side, you can consider the issue closed.

**Comment by jvillard** [comment]
No spam at all, the documentation was outdated and thanks to you it's been updated. Thanks!

**Comment by tregua87** [comment]
Sorry @jvillard, last thing.

May I ask when was the last commit where this checker was enabled, please?

**Comment by jvillard** [comment]
Anything before 80b3d080ceb73e20b05967ac16db7459b80b26a7 would have it. The immediate parent is e90e6c8bf07d7f33a40f2bc264d88fd799cf4807. It should also be present in infer 0.13.1.
